### PR TITLE
Only validate or process manifests that have changed

### LINKED ISSUE #12: Validate only relevant boutiques/gears in a given PR
Validating unchanged botiques/gears impacts performance, and also can cause PRs to fail validation when docker images for unrelated gears become unavailable.

### PR DESCRIPTION
**Pull request by ryansanford**
Resolves #12 

@gsfr Please review

### CODE REVIEW

**Comment by ryansanford** [comment]
Heads up to @kofalt -- expecting this will resolve your PR.

File: bin/process-manifests.sh [hunk 1]
```diff
@@ -215,24 +215,30 @@ function process_manifests() {
 
 
 >&2 echo "On branch $GIT_BRANCH"
-manifests=$( find $GEARS_DIR $BOUTIQUES_DIR -iname "*.json" )
+if [ -z "$GIT_COMMIT_SENTINEL" ]; then
```
Comment (kofalt) [inline bin/process-manifests.sh]: Document this variable?

File: bin/process-manifests.sh [hunk 2]
```diff
@@ -215,24 +215,30 @@ function process_manifests() {
...
+    >&2 echo "Using all manifests"
+    manifests=$( find $GEARS_DIR $BOUTIQUES_DIR -iname "*.json" )
+    >&2 echo "$manifests"
+else
+    >&2 echo "Using updated manifests"
+    manifests=$( git diff --name-only $GIT_COMMIT_SENTINEL | grep -e "^$GEARS_DIR/..*$" -e "^$BOUTIQUES_DIR/..*$" || true)
```
Comment (kofalt) [inline bin/process-manifests.sh]: How confident are you in this line? Why is the grep here different than just `*.json` as it is above?

File: bin/process-manifests.sh (hunk 1 above)
Comment (ryansanford) [inline bin/process-manifests.sh]: Reasonable request, since I need to remind myself how that works every time.

File: bin/process-manifests.sh (hunk 2 above)
Comment (ryansanford) [inline bin/process-manifests.sh]: The echo comments explain the intended difference. Maybe I don't understand the question? One grabs all the manifests, and the other grabs only manifests changed since the commit id recorded in `$GIT_COMMIT_SENTINEL`

File: bin/process-manifests.sh (hunk 1 above)
Comment (gsfr) [inline bin/process-manifests.sh]: How about this: git commit hash of last successful manifest processing?

File: bin/process-manifests.sh (hunk 2 above)
Comment (gsfr) [inline bin/process-manifests.sh]: I think the question is, why can't we just do
```
git diff --name-only $GIT_COMMIT_SENTINEL | grep -i "*.json"
```
Is that right, @kofalt?

Comment (kofalt) [inline bin/process-manifests.sh]: Basically. I didn't see that the find above is limiting to the boutique and gear folders.

We can leave this grep as it is, or we can change it around to clarify. I'm fine with either.

**Comment by kofalt** [comment]
LGTM!

File: bin/process-manifests.sh (hunk 2 above)
Comment (gsfr) [inline bin/process-manifests.sh]: The line is unchanged from before, so I'd be inclined to keep it as is.
